config/routes.rb
Rails.application.routes.draw do
  get 'contact_us' => 'page#contact_us'
  get 'menu' => 'page#menu'
  devise_for :users
  root to: 'page#home', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Menu.all
  end

  def show; end

  def new
    @menu = Menu.new
  end

  def edit; end

  def create
    @menu= Menu.new(post_params)
    @menu.user_id = current_user.id if user_signed_in?
    if @menu.save
      redirect_to @menu
    else
      render 'new'
    end
  end

  def update
    if @menu.update(post_params)
      redirect_to @menu
    else
      render 'edit'
    end
  end

  def destroy
    @menu.destroy
    redirect_to dashboard_path
  end

  private

  def set_post
    @menu = Menu.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:first_course, :main_course, :drink, :price)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home; end
  def contact_us; end
  def menu; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityFood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="col-sm-12">
    <%= yield %>
    </div>
  </body>
</html>

app/views/menu/_form.html.erb
<%= form_with model: @menu do |f| %>
<% if menu.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(menu.errors.count, "error") %>
      prohibited this menu from being saved:</h2>
    <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= f.file_field :image %>
</div>
<div class="form-group">
  <%= f.label :first_course %><br />
  <%= f.text_area :first_course %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/menu/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Show', @post %>
<%= link_to 'Back', dashboard_path %>

app/views/menu/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <h1>Top Posts</h1>
  <% else %>
    <h1>Oop! No matching posts ...</h1>
  <% end %>
  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
        <%=image_tag post.thumbnail %>
      <% end %>
    </div>
  <% end %>
</div>
</div>

app/views/menu/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', home_path %>

app/views/menu/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.thumbnail, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to profile_path(@post.user.username) do %>
          <%= image_tag @post.user.avatar %>
        <% end %>
      <% end %>
    </div>
    <%= link_to @post.user.username, profile_path(@post.user.username), class: 'username' %>
  </div>
  <div class="description">
    <%= render "shared/likes" %>
    <p><%= @post.likes.count %>
      <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <%= @post.body %><hr/>
    <%= render "shared/comments" %>
    <div class="input-group mb-3">
      <%= form_with model: [@post, @comment], local: true do |f| %>
      <hr/>
      <div class="input-group">
        <%= f.text_field :comment, placeholder:"Add comment here...", class: "form-control" %><hr/>
        <%= f.submit "Post",class:"btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>
<div class="delete">
  <% if current_user.posts.exists?(@post.id) %>
    <%= link_to 'Remove',post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Edit', edit_post_path(@post) %>
  <% end %>
  <%= link_to 'Back', dashboard_path %>
</div>
</div>
</div>

app/views/page/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Welcome to CiryFood</h1>
    <p class="lead">
      <%= link_to 'Menu', menu_path, class:'btn btn-primary btn-lg' %>
      <%= link_to 'Contact Us', contact_us_path, class:'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">CityFood</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="page#menu">Menu</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contact_us_path">Contact Us</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>